{% set version = "1.7.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tidycensus
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidycensus_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidycensus/tidycensus_{{ version }}.tar.gz
  sha256: 5fbee8138584c25e326cae39e0928f6a993472b77db6be9626999cc5eb15c484

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dplyr >=1.0.0
    - r-httr
    - r-jsonlite >=1.5.0
    - r-purrr
    - r-rappdirs
    - r-readr
    - r-rlang
    - r-rvest
    - r-sf
    - r-stringr
    - r-tidyr >=1.0.0
    - r-tigris
    - r-units
    - r-xml2
  run:
    - r-base
    - r-dplyr >=1.0.0
    - r-httr
    - r-jsonlite >=1.5.0
    - r-purrr
    - r-rappdirs
    - r-readr
    - r-rlang
    - r-rvest
    - r-sf
    - r-stringr
    - r-tidyr >=1.0.0
    - r-tigris
    - r-units
    - r-xml2

test:
  commands:
    - $R -e "library('tidycensus')"           # [not win]
    - "\"%R%\" -e \"library('tidycensus')\""  # [win]

about:
  home: https://github.com/walkerke/tidycensus
  license: MIT
  summary: An integrated R interface to the decennial US Census and American Community Survey APIs and the US Census Bureau's geographic boundary files. Allows R users to return Census and ACS data as tidyverse-ready data frames, and optionally returns a list-column with feature geometry for all Census geographies.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn
